version: '{build}'

image: Visual Studio 2019

# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - bundle --version
  - bundle install
  - ridk.cmd exec bundle exec rake compile
build: off
test_script:
  # - bundle exec rake test
  - bundle exec rake test TESTOPTS=-v

# https://www.appveyor.com/docs/installed-software/#ruby
environment:
  matrix:
    - ruby_version: "31-x64"
    - ruby_version: "31"
    - ruby_version: "30-x64"
    - ruby_version: "30"
    - ruby_version: "27-x64"
    - ruby_version: "27"
    - ruby_version: "26-x64"
    - ruby_version: "26"
    - ruby_version: "25-x64"
    - ruby_version: "25"
    - ruby_version: "24-x64"
    - ruby_version: "24"

for:
-
  matrix:
    only:
      - ruby_version: "31-x64"
      - ruby_version: "27-x64"
      - ruby_version: "27"
      - ruby_version: "26-x64"
      - ruby_version: "26"
  install:
    - ps: if ($ENV:ruby_version -ne "31-x64") { .\ruby_install.ps1 }
    - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
    - ruby --version
    - gem --version
    - bundle --version
    - ps: if ($ENV:ruby_version -eq "31-x64") { ridk.ps1 install 1 3 }
    - ridk.cmd exec bundle install
    - ridk.cmd exec bundle exec rake compile
